[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmd = "npm ci"

[phases.build]
cmd = "npm run build -- --configuration production"

[start]
cmd = "npx http-server dist/supercopias-frontend --spa -p $PORT"